# Generated by Django 5.1.1 on 2024-10-31 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userUid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
