# Generated by Django 5.1.1 on 2024-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0002_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='user',
        ),
    ]
