# Generated by Django 5.1.1 on 2024-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0006_cart_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='nbPers',
            field=models.IntegerField(default=1),
        ),
    ]
