# Generated by Django 5.1.1 on 2024-12-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0007_competition_price_alter_offer_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quanity',
        ),
    ]
