# Generated by Django 5.1.1 on 2024-12-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0009_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='offer',
            field=models.FloatField(default=0.0),
        ),
    ]
