# Generated by Django 5.1.1 on 2024-12-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0011_alter_cart_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
