# Generated by Django 5.1.1 on 2024-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0012_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
