# Generated by Django 5.1.1 on 2024-12-21 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0013_cart_ispaid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateTimeField()),
                ('cardNumber', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('paymentUid', models.UUIDField(default=uuid.uuid4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
