# Generated by Django 5.1.1 on 2025-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cartAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
