# Generated by Django 5.1.1 on 2025-01-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0015_payment_cartamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
