# Generated by Django 5.1.1 on 2025-01-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_app', '0019_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
